rivet-gg/toolchain

cli/src/commands/version.rs, cli/tpl/workflows/rivet-publish.yaml
Enables using `rivet.version.{namespace}.toml` files to override config parameters for specific namespaces.
=> Namespace-level config overrides

CHANGELOG.md, cli/src/commands/dev.rs, cli/src/commands/engine/mod.rs, cli/src/commands/engine/unreal.rs, cli/src/commands/init.rs, cli/src/commands/token/create/dev.rs, cli/src/commands/token/create/mod.rs, cli/src/commands/token/mod.rs, cli/src/main.rs
- Fix windows install path
- Rename deploy command
- Update install docs
- Simplify token create command
- Update CHANGELOG.md
=> Simplify rivet token create dev

cli/src/commands/init.rs
=> Auto remove .rivet dir on `rivet init`

CHANGELOG.md, cli/src/commands/deploy.rs, cli/src/commands/dev.rs, cli/src/commands/mod.rs, cli/src/commands/version.rs, cli/src/main.rs
=> Move deploy command from rivet version deploy to rivet deploy

CHANGELOG.md, cli/src/commands/ci.rs, cli/src/commands/config.rs, cli/src/commands/deploy.rs, cli/src/commands/init.rs, cli/src/commands/mod.rs, cli/src/commands/token/create/dev.rs, cli/src/commands/version.rs, cli/src/main.rs, cli/tests/version.rs, cli/tpl/ci/github/head.yml
=> Move rivet version validate-config to rivet config validate

CHANGELOG.md, cli/src/commands/token/create/mod.rs, cli/src/commands/token/create/pub_ns.rs, cli/src/util/global_config.rs
=> Add rivet token create public-namespace command

CHANGELOG.md, cli/src/commands/mod.rs, cli/src/commands/unlink.rs, cli/src/main.rs, cli/src/util/global_config.rs
=> Add unlink command

CHANGELOG.md, cli/src/commands/init.rs
=> Add custom engine to init command

CHANGELOG.md, cli/Cargo.toml, cli/src/util/os.rs
=> Fix error compiling with `nix` on Windows

README.md
=> Document installed binary name

CHANGELOG.md, cli/src/main.rs
=> Remove explicit true in --telemetry-disabled flag

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/src/util/telemetry.rs
=> Replace uname with sysinfo crate

cli/src/commands/sidekick.rs, cli/src/main.rs
This will close PLG-1
> ## TL;DR
> This pull request introduces changes to the `sidekick.rs` and `main.rs` files. The changes include renaming a variable, adding a new subcommand, and implementing token validation.
> 
> ## What changed
> In `sidekick.rs`, the `device_link_url` variable was renamed to `device_link_token` for better clarity. A new subcommand `GetToken` was added to retrieve the token from the CLI. The `wait_for_login` function was updated to use the renamed variable. A new function `validate_token` was added to check if a token is present.
> 
> In `main.rs`, the token is now read before the sidekick sign-in is called. The `WaitForLogin` command now uses the renamed variable. The `CheckLoginState` command now calls the new `validate_token` function. If the command is …
=> Add commands to get token

cli/src/commands/sidekick/get_dev_namespace_token.rs, cli/src/commands/sidekick/get_pub_namespace_token.rs, cli/src/commands/sidekick/mod.rs
=> Adds `get-namespace-dev-token` command

cli/src/commands/sidekick/mod.rs, cli/src/main.rs
=> Fixing terminals

cli/src/commands/sidekick/mod.rs, cli/src/commands/sidekick/unlink.rs, cli/src/commands/unlink.rs
=> Adds unlink functionality

README.md
=> Fix Windows PowerShell install copy pasta command

CHANGELOG.md, cli/src/commands/deploy.rs, cli/src/commands/version.rs
=> Make rivet.game url dynamic

cli/src/commands/deploy.rs, cli/src/commands/game.rs, cli/src/commands/ns.rs, cli/src/commands/version.rs, scripts/check_links.rs
=> Make hub.rivet.gg dynamic

.github/workflows/release.yml
=> Use Nix in cargo-dist workflow

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/src/commands/docker/archive.rs, cli/src/util/users.rs
This PR is the equivalent of playing the floor is lava with the Windows file system and path conventions.
=> Update OCI bundle archival process to operate on TAR streams

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/src/commands/cdn.rs, cli/src/commands/docker/push.rs, cli/src/util/term.rs, cli/src/util/upload.rs
=> Add progress bars to uploads

cli/src/commands/sidekick/mod.rs
=> Change mac script to run from proj directory

cli/src/commands/deploy.rs
=> Remove link to version dashboard

Cargo.toml, scripts/shellcheck.sh
=> Remove invalid install scripts

CHANGELOG.md, cli/src/commands/token/create/dev.rs, cli/src/commands/token/create/pub_ns.rs
=> Print newline to stderr to hide zsh eol mark

CHANGELOG.md, cli/src/commands/cdn.rs, cli/src/commands/docker/push.rs, cli/src/commands/run.rs, cli/src/util/term.rs, cli/src/util/upload.rs
=> Print only one progress bar for >40 files

cli/src/commands/backend/deploy.rs, cli/src/commands/backend/mod.rs, cli/src/main.rs
=> feat: run opengb using docker by default

rivet-toolchain/src/ctx.rs
=> fix: disable hyper connection pooling

rivet-toolchain/src/backend/mod.rs
=> fix: envfile race condition

rivet-toolchain/src/backend/mod.rs
=> fix: clean opengb container after run

rivet-toolchain/src/backend/mod.rs
This closes RVTEE-469
This is improved in #326
=> fix: remove tty for docker runs

rivet-toolchain/src/backend/mod.rs, rivet-toolchain/src/tasks/backend_dev.rs, rivet-toolchain/src/tasks/backend_sdk_gen.rs
=> fix: only publish port for backend

rivet-toolchain/src/backend/mod.rs, rivet-toolchain/src/tasks/backend_dev.rs, rivet-toolchain/src/tasks/backend_sdk_gen.rs, rivet-toolchain/src/tasks/deploy/backend.rs
=> fix: add tty only for backend

packages/backend/toolchain/build/plan/project.ts
=> fix(backend): apply not getting ran
